database:

  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password: sa

  # the JDBC URL
  url: jdbc:h2:./target/initial

  #Properties specific to selected driver
  properties:
      charSet: UTF-8
      hibernate.dialect: org.hibernate.dialect.H2Dialect